#!/bin/bash
touch /tmp/done
echo "Started" >> /tmp/done

# AliEC2 Env-vars
# URL of the AliEC2 web service
export ALIEC2_URL="http://10.0.0.35:3000"
# The interval which the CernVM instance should update AliEC2 in seconds
export ALIEC2_INTERVAL=60

__updateStatus() {
	wget $ALIEC2_URL/alive/$(hostname)
	sleep $ALIEC2_INTERVAL
}

# Run the update loop in the background.
__updateStatus &

echo "Creating startup-script" >> /tmp/done
# start of alien-generated script
cat > agent_startup.sh << 'ALIEC2_EOF'

export PATH=$PATH:/cvmfs/alice.cern.ch/bin/
export ALIEN_ORGANISATION=ALIENBERGEN
export ALIEN_WORKDIR=$HOME/alien/work #Maa stemme med verdi i alienbergen.conf for WORK_DIR
export ALIEN_CACHE=$HOME/alien/cache  #Maa stemme med verdi i alienbergen.conf for CACHE_DIR
export ALIEN_DOMAIN=os.hib.no
export ALIEN_LDAP_DN="cs.hib.no:8389/o=ALIENBERGEN,dc=hib,dc=no"
